### ISSUE TITLE
Can't turn on notifications

### ISSUE THREAD

**Issue by bochoven** [grahamgilbert/munki-dnd#1]
I don't seem to be able to turn on notifications after I've turned them off.

**Comment by grahamgilbert** [comment]
Yes, this is by design. I've never, ever met a user who would turn them on! MSC will still function if the user opens it.

**Comment by bochoven** [comment]
Perhaps you're right, but OSX dnd has also the ability to turn notifications back on. And **I** would like the ability to turn them on again.

**Comment by grahamgilbert** [comment]
We'll see. It will require a bit of restructuring if I decided to do this.

**Comment by grahamgilbert** [comment]
This is implemented, pushing release shortly.
